<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.vidocq</groupId>
    <artifactId>vidocq-parent</artifactId>
    <version>0.1.1-SNAPSHOT</version>
    <relativePath />
  </parent>

  <groupId>io.vidocq.grimm</groupId>
  <artifactId>grimm-parent</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>Grimm</name>
  <description>MicroProfile OpenAPI 4.1 implementation for Vidocq</description>
  <url>https://codeberg.org/Vidocq/grimm</url>

  <developers>
    <developer>
      <name>Yann Blazart</name>
      <email>yann.blazart@gmail.com</email>
    </developer>
    <developer>
      <name>Antoine Sabot-Durand</name>
      <email>antoine@sabot-durand.net</email>
    </developer>
  </developers>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>

  <scm>
    <connection>scm:git:https://codeberg.org/Vidocq/grimm.git</connection>
    <developerConnection>scm:git:ssh://git@codeberg.org/Vidocq/grimm.git</developerConnection>
    <url>https://codeberg.org/Vidocq/grimm</url>
    <tag>HEAD</tag>
  </scm>

  <modules>
    <module>grimm-core</module>
    <module>grimm-cdi-vauban</module>
    <module>grimm-bench</module>
    <module>grimm-examples</module>
  </modules>

  <properties>
    <version.mp.openapi>4.1</version.mp.openapi>
    <version.ravel.mp.config>0.1.0-SNAPSHOT</version.ravel.mp.config>
    <version.jakarta.ws.rs>4.0.0</version.jakarta.ws.rs>
    <version.jakarta.cdi>4.1.0</version.jakarta.cdi>
    <version.jakarta.annotation>3.0.0</version.jakarta.annotation>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.eclipse.microprofile.openapi</groupId>
        <artifactId>microprofile-openapi-api</artifactId>
        <version>${version.mp.openapi}</version>
      </dependency>
      <dependency>
        <groupId>io.vidocq.ravel</groupId>
        <artifactId>ravel-mp-config-api</artifactId>
        <version>${version.ravel.mp.config}</version>
      </dependency>
      <dependency>
        <groupId>jakarta.ws.rs</groupId>
        <artifactId>jakarta.ws.rs-api</artifactId>
        <version>${version.jakarta.ws.rs}</version>
      </dependency>
      <dependency>
        <groupId>jakarta.enterprise</groupId>
        <artifactId>jakarta.enterprise.cdi-api</artifactId>
        <version>${version.jakarta.cdi}</version>
      </dependency>
      <dependency>
        <groupId>jakarta.annotation</groupId>
        <artifactId>jakarta.annotation-api</artifactId>
        <version>${version.jakarta.annotation}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>


