/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
module io.vidocq.grimm.cdi.vauban {
  requires io.vidocq.grimm.core;
  // GrimmModelCache hands out the OpenAPI model, OpenApiResource answers a JAX-RS Response:
  // a consumer of this module's API reads both.
  requires transitive org.eclipse.microprofile.openapi;
  requires transitive jakarta.ws.rs;
  requires jakarta.cdi;
  requires jakarta.inject;
  requires jakarta.annotation;
  requires org.eclipse.microprofile.config;
  // Compile-only: the service type of the APT-generated _VaubanComponents below.
  requires static io.vidocq.vauban.api;

  exports io.vidocq.grimm.cdi;

  provides jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension
      with io.vidocq.grimm.cdi.GrimmExtension;

  // In-module instantiation and field injection of this package's beans, generated by the Vauban
  // processor: on the module path the container needs no `opens … to io.vidocq.vauban.core`.
  provides io.vidocq.vauban.api.VaubanComponentProvider
      with io.vidocq.grimm.cdi._VaubanComponents;
}

